from django.conf.urls import url, include
from django.contrib import admin
import django.contrib.auth.views
import core.views

urlpatterns = [
    url(r'^sign_up$', core.views.signup, name='sign_up'),
    url(r'^home$', core.views.home, name="home"),
    url(r'^profile/(?P<user_id>[0-9]+)$', core.views.profile, name="profile"),
    url(r'^sign_in$', django.contrib.auth.views.login, {'template_name': 'core/sign_in.html'}, name='sign_in'),
    url(r'^sign_out$', django.contrib.auth.views.logout_then_login, {'login_url': 'core/sign_in.html'},
        name='sign_out'),
    url(r'^new-meme$', core.views.new_meme, name='new_meme'),
    url(r'^new-meme-with-id/(?P<meme_bg_id>\d+)$', core.views.new_meme_with_id, name='new_meme_with_id'),
    url(r'^log-out$', django.contrib.auth.views.logout_then_login, name='log_out'),
    url(r'^setting$', core.views.setting, name='setting'),
    url(r'^update$', core.views.update_info, name='update'),
    url(r'^create_meme$', core.views.create_meme, name='create_meme'),
    url(r'^create_meme/meme_war/(?P<thread_id>[0-9]+)/(?P<user_id>[0-9]+)$', core.views.create_meme_in_meme_war,
        name='create_meme_in_meme_war'),
    url(r'^create_meme/(?P<meme_bg_id>\d+)$', core.views.create_meme, name='create_meme'),
    url(r'^view_new_meme/(?P<meme_id>\d+)$', core.views.view_new_meme, name='view_new_meme'),
    url(r'^show_meme_image/(?P<meme_id>\d+)$', core.views.show_meme_photo, name='show_meme_photo'),
    url(r'^get_meme_bg/(?P<meme_bg_id>\d+)$', core.views.get_meme_bg, name='get_meme_bg'),
    url(r'^get_photo/(?P<user_id>[0-9]+)$', core.views.get_photo, name='get_photo'),
    url(r'^get_profile_background$', core.views.get_profile_background, name='profile_background'),
    url(r'^favorite/(?P<meme_id>[0-9]+)$', core.views.favorite),
    url(r'^meme-war/(?P<thread_id>[0-9]+)$', core.views.meme_war, name='meme_war'),
    url(r'^reply-in-meme-war/(?P<thread_id>[0-9]+)/(?P<meme_id>[0-9]+)/(?P<user_id>[0-9]+$)',
        core.views.reply_in_meme_war, name='reply_in_meme_war'),
    url(r'^sort/(?P<string>[\w\-]+)/$', core.views.sort_meme, name='sort'),
    url(r'^search/$', core.views.search, name='search'),
    url(r'^edit-meme/(?P<meme_bg_id>\d+)$', core.views.edit_meme, name='edit_meme'),
    url(r'^get-notified', core.views.get_notified, name='get_notified'),
    url(r'^read-notification/(?P<message_id>\d+)$', core.views.read_message, name='read_message'),
    url(r'^password/change/$', django.contrib.auth.views.password_change, name="password_change"),
    url(r'^password/change/done/$', django.contrib.auth.views.password_change_done, name="password_change_done"),
    url(r'^password/reset/$', django.contrib.auth.views.password_reset, name="password_reset"),
    url(r'^password/reset/done/$', django.contrib.auth.views.password_reset_done, name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        django.contrib.auth.views.password_reset_confirm, name="password_reset_confirm"),
    url(r'^password/done/$', django.contrib.auth.views.password_reset_complete, name="password_reset_complete"),
    url(r'^activate/(?P<user_id>[0-9]+)$', core.views.activate, name='activate'),
]
